length_name_maximum: 50
length_email_maximum: 255
length_password_minimum: 6
_true: "1"
host_heroku: "https://ancient-falls-61196.herokuapp.com"
host: "http://localhost:3000"
address: "smtp.gmail.com"
port: "587"
authentication: :plain,
domain: "gmail.com"
two_hours: 2
host_local: "localhost"
port_local: 3000
tour_quantity_maximum: 50
